name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'minor'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'patch'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'

exclude-labels:
  - 'duplicate'
  - 'invalid'
  - 'wontfix'
  - 'skip-changelog'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # Escape characters that have special meaning in Markdown

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
  - label: 'ci'
    files:
      - '.github/workflows/*'

template: |
  ## ValidatorKit $RESOLVED_VERSION

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
